-- RSVP table for the wedding website.
-- Run this once in your Supabase project: SQL Editor → New query → paste → Run.
-- Safe to re-run: every statement is a no-op if it has already been applied.

create table if not exists rsvps (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  attending boolean not null,
  created_at timestamptz not null default now()
);

-- Contact details + a message for the couple.
alter table rsvps add column if not exists email text;
alter table rsvps add column if not exists phone text;
alter table rsvps add column if not exists wishes text;
alter table rsvps add column if not exists updated_at timestamptz;

-- Secret per-guest token (64 hex chars) behind the "edit your RSVP" link that
-- is emailed to each guest. Generated by the database on insert.
alter table rsvps add column if not exists edit_token text not null
  default replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', '');
create unique index if not exists rsvps_edit_token_key on rsvps (edit_token);

-- Lock the table down: no anonymous/public access. Only the Cloudflare Worker,
-- using the service_role key, can read or write (service_role bypasses RLS).
alter table rsvps enable row level security;

-- Travel plans submitted from the Travel page, so arrivals, vans and hotels can
-- be compiled in one place. Dates/times are local to the airport.
create table if not exists travel_plans (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  phone text,
  party_size integer not null default 1,
  party_names text,
  arrival_airport text,
  arrival_date date not null,
  arrival_time text,
  arrival_flight text,
  departure_airport text,
  departure_date date,
  departure_time text,
  departure_flight text,
  needs_transfer boolean,
  hotel text,
  notes text,
  edit_token text not null
    default replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', ''),
  created_at timestamptz not null default now(),
  updated_at timestamptz
);
create unique index if not exists travel_plans_edit_token_key on travel_plans (edit_token);
alter table travel_plans enable row level security;
